### ISSUE TITLE
how to tune the 3d cartographer  for my vel-16 data

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer_ros#501] opened 2017-09-11 02:00 UTC
hello, I am tuning cartographer 3d for my vel-16 data,but the effect is very confusing, The /scan_matched_points2 laser frame has a great jump,can you help me?
configuration file , launch file, urdf file and png file is [here](https://github.com/sunmk2006/cartographer_ros)
the bag file is [here](https://pan.baidu.com/s/1boJwRYf)

**Comment by SirVer** [comment] 2017-10-12 13:50
I assume this a duplicate of #509. Closing this issue as duplicate.

**Closed by SirVer** 2017-10-12 13:50 UTC
