### ISSUE TITLE
Correction in pure localization result by manual

### ISSUE THREAD

**Issue by nnn112358** [googlecartographer/cartographer_ros#489] opened 2017-08-23 22:35 UTC
I tried pure localization function in cartographer ,and confirmed that the performance is great compared to ACML.

By the way, there is one necessary function, I want to remodel.
I want to fix cartographer's localization　result position manually.
For example, in ACML, it can be corrected with the 2D pose estimate button in rviz.

What data is stored in cartographer's localization　result?
And is it rewritable?

**Comment by damonkohler** [comment] 2017-08-24 07:24
Duplicate of googlecartographer/cartographer#469

**Closed by damonkohler** 2017-08-24 07:24 UTC
